hasCJKLanguage = true
theme="material-design"
baseurl = "https://easy-hugo.firebaseapp.com"
languageCode = "ja"
title = "PPAP blog"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
copyright = "©2017 PPAP blog powered by Hugo"

[params]
  blogurl = "https://easy-hugo.firebaseapp.com"
  blogdomain = "easy-hugo.firebaseapp.com"
  github = "masasam"
  twitter = "masasamsama"
  # headerCover = "images/headerCover.jpg"
  # footerCover = "images/footerCover.jpg"
  googleAnalyticsUserID = "UA-************"
